const TOGGLE_TASK_EDIT = 'TOGGLE_TASK_EDIT';
const RESET_TASKS_EDIT = 'RESET_TASKS_EDIT';
// const ADD_ALL_TASKS_EDIT = 'ADD_ALL_TASKS_EDIT';
// const REMOVE_ALL_TASKS_EDIT = 'REMOVE_ALL_TASKS_EDIT';

export default {
    TOGGLE_TASK_EDIT,
    RESET_TASKS_EDIT,
    // ADD_ALL_TASKS_EDIT,
    // REMOVE_ALL_TASKS_EDIT
};
