const ADD_TASK = 'ADD_TASK';
const DONE_TASKS = 'DONE_TASKS';
const REMOVE_TASKS = 'REMOVE_TASKS';
// const DONE_ALL_TASKS = 'DONE_ALL_TASKS'
// const REMOVE_ALL_TASKS = 'REMOVE_ALL_TASKS';

export default {
    ADD_TASK,
    DONE_TASKS,
    REMOVE_TASKS,
    // DONE_ALL_TASKS,
    // REMOVE_ALL_TASKS
};
